const products = [
    {
        id: 1,
        name: "Stylish Sunglasses",
        price: 50,
        salePercentage: 20, // 20% off
        image: "images/p1.jpg",
        smallImages: ["images/p1_thumb1.jpg", "images/p1_thumb2.jpg", "images/p1_thumb3.jpg"],
        category: "sale",
        size: "Medium",
        material: "plastic",
        style: "frameless",
        description: "Stylish sunglasses with UV protection."
    },
    {
        id: 2,
        name: "Classic Eyeframe",
        price: 70,
        salePercentage: 35, // 35.71% off
        image: "images/p2.jpg",
        smallImages: ["images/p2_thumb1.jpg", "images/p2_thumb2.jpg", "images/p2_thumb3.jpg"],
        category: "eyeframes",
        size: "Large",
        material: "titan",
        style: "full-rim",
        description: "Classic eyeframe with a modern twist."
    },
    {
        id: 3,
        name: "Modern Sunglasses",
        price: 60,
        image: "images/p3.jpg",
        smallImages: ["images/p3_thumb1.jpg", "images/p3_thumb2.jpg", "images/p3_thumb3.jpg"],
        category: "sunglasses",
        size: "Small",
        material: "iron",
        style: "semi-rimless",
        description: "Modern sunglasses with a sleek design."
    },
    {
        id: 4,
        name: "Elegant Eyeframe",
        price: 80,
        image: "images/p4.jpg",
        smallImages: ["images/p4_thumb1.jpg", "images/p4_thumb2.jpg", "images/p4_thumb3.jpg"],
        category: "eyeframes",
        size: "Medium",
        material: "plastic",
        style: "combination",
        description: "Elegant eyeframe for a sophisticated look."
    },
    {
        id: 5,
        name: "Elegant Eyeframe",
        price: 80,
        image: "images/p5.jpg",
        smallImages: ["images/p5_thumb1.jpg", "images/p5_thumb2.jpg", "images/p5_thumb3.jpg"],
        category: "eyeframes",
        size: "Medium",
        material: "titan",
        style: "half-eye",
        description: "Elegant eyeframe for a sophisticated look."
    },
    {
        id: 6,
        name: "Elegant Eyeframe",
        price: 80,
        salePercentage: 43, // 43.75% off
        image: "images/p6.jpg",
        smallImages: ["images/p6_thumb1.jpg", "images/p6_thumb2.jpg", "images/p6_thumb3.jpg"],
        category: "sale",
        size: "Medium",
        material: "iron",
        style: "low-bridge",
        description: "Elegant eyeframe for a sophisticated look."
    },
    {
        id: 7,
        name: "Trendy Sunglasses",
        price: 55,
        image: "images/p7.jpg",
        smallImages: ["images/p7_thumb1.jpg", "images/p7_thumb2.jpg", "images/p7_thumb3.jpg"],
        category: "sunglasses",
        size: "Large",
        material: "plastic",
        style: "wire",
        description: "Trendy sunglasses with a modern design."
    },
    {
        id: 8,
        name: "Vintage Eyeframe",
        price: 75,
        image: "images/p8.jpg",
        smallImages: ["images/p8_thumb1.jpg", "images/p8_thumb2.jpg", "images/p8_thumb3.jpg"],
        category: "eyeframes",
        size: "Small",
        material: "titan",
        style: "full-rim",
        description: "Vintage eyeframe with a classic look."
    },
    {
        id: 9,
        name: "Stylish Sunglasses",
        price: 50,
        salePercentage: 20, // 20% off
        image: "images/p1.jpg",
        smallImages: ["images/p1_thumb1.jpg", "images/p1_thumb2.jpg", "images/p1_thumb3.jpg"],
        category: "sale",
        size: "Medium",
        material: "plastic",
        style: "frameless",
        description: "Stylish sunglasses with UV protection."
    },
    {
        id: 10,
        name: "Classic Eyeframe",
        price: 70,
        salePercentage: 35, // 35.71% off
        image: "images/p2.jpg",
        smallImages: ["images/p2_thumb1.jpg", "images/p2_thumb2.jpg", "images/p2_thumb3.jpg"],
        category: "eyeframes",
        size: "Large",
        material: "titan",
        style: "full-rim",
        description: "Classic eyeframe with a modern twist."
    },
    {
        id: 11,
        name: "Modern Sunglasses",
        price: 60,
        image: "images/p3.jpg",
        smallImages: ["images/p3_thumb1.jpg", "images/p3_thumb2.jpg", "images/p3_thumb3.jpg"],
        category: "sunglasses",
        size: "Small",
        material: "iron",
        style: "semi-rimless",
        description: "Modern sunglasses with a sleek design."
    },
    {
        id: 12,
        name: "Elegant Eyeframe",
        price: 80,
        image: "images/p4.jpg",
        smallImages: ["images/p4_thumb1.jpg", "images/p4_thumb2.jpg", "images/p4_thumb3.jpg"],
        category: "eyeframes",
        size: "Medium",
        material: "plastic",
        style: "combination",
        description: "Elegant eyeframe for a sophisticated look."
    },
    {
        id: 13,
        name: "Elegant Eyeframe",
        price: 80,
        image: "images/p5.jpg",
        smallImages: ["images/p5_thumb1.jpg", "images/p5_thumb2.jpg", "images/p5_thumb3.jpg"],
        category: "eyeframes",
        size: "Medium",
        material: "titan",
        style: "half-eye",
        description: "Elegant eyeframe for a sophisticated look."
    },
    {
        id: 14,
        name: "Elegant Eyeframe",
        price: 80,
        salePercentage: 43, // 43.75% off
        image: "images/p6.jpg",
        smallImages: ["images/p6_thumb1.jpg", "images/p6_thumb2.jpg", "images/p6_thumb3.jpg"],
        category: "sale",
        size: "Medium",
        material: "iron",
        style: "low-bridge",
        description: "Elegant eyeframe for a sophisticated look."
    },
    {
        id: 15,
        name: "Trendy Sunglasses",
        price: 55,
        image: "images/p7.jpg",
        smallImages: ["images/p7_thumb1.jpg", "images/p7_thumb2.jpg", "images/p7_thumb3.jpg"],
        category: "sunglasses",
        size: "Large",
        material: "plastic",
        style: "wire",
        description: "Trendy sunglasses with a modern design."
    },
    {
        id: 16,
        name: "Vintage Eyeframe",
        price: 75,
        image: "images/p8.jpg",
        smallImages: ["images/p8_thumb1.jpg", "images/p8_thumb2.jpg", "images/p8_thumb3.jpg"],
        category: "eyeframes",
        size: "Small",
        material: "titan",
        style: "full-rim",
        description: "Vintage eyeframe with a classic look."
    },
    {
        id: 17,
        name: "Stylish Sunglasses",
        price: 50,
        salePercentage: 20, // 20% off
        image: "images/p1.jpg",
        smallImages: ["images/p1_thumb1.jpg", "images/p1_thumb2.jpg", "images/p1_thumb3.jpg"],
        category: "sale",
        size: "Medium",
        material: "plastic",
        style: "frameless",
        description: "Stylish sunglasses with UV protection."
    },
    {
        id: 18,
        name: "Classic Eyeframe",
        price: 70,
        salePercentage: 35, // 35.71% off
        image: "images/p2.jpg",
        smallImages: ["images/p2_thumb1.jpg", "images/p2_thumb2.jpg", "images/p2_thumb3.jpg"],
        category: "eyeframes",
        size: "Large",
        material: "titan",
        style: "full-rim",
        description: "Classic eyeframe with a modern twist."
    },
    {
        id: 19,
        name: "Trendy Sunglasses",
        price: 55,
        image: "images/p3.jpg",
        smallImages: ["images/p3_thumb1.jpg", "images/p3_thumb2.jpg", "images/p3_thumb3.jpg"],
        category: "sale",
        size: "Large",
        material: "plastic",
        style: "semi-rimless",
        description: "Trendy sunglasses with a modern design."
    },
    {
        id: 20,
        name: "Classic Eyeframe",
        price: 70,
        image: "images/p4.jpg",
        smallImages: ["images/p4_thumb1.jpg", "images/p4_thumb2.jpg", "images/p4_thumb3.jpg"],
        category: "eyeframes",
        size: "Medium",
        material: "titan",
        style: "full-rim",
        description: "Classic eyeframe with a modern twist."
    },
    {
        id: 21,
        name: "Modern Sunglasses",
        price: 60,
        image: "images/p5.jpg",
        smallImages: ["images/p5_thumb1.jpg", "images/p5_thumb2.jpg", "images/p5_thumb3.jpg"],
        category: "sunglasses",
        size: "Small",
        material: "iron",
        style: "frameless",
        description: "Modern sunglasses with a sleek design."
    },
    {
        id: 22,
        name: "Elegant Eyeframe",
        price: 80,
        image: "images/p6.jpg",
        smallImages: ["images/p6_thumb1.jpg", "images/p6_thumb2.jpg", "images/p6_thumb3.jpg"],
        category: "eyeframes",
        size: "Large",
        material: "plastic",
        style: "combination",
        description: "Elegant eyeframe for a sophisticated look."
    },
    {
        id: 23,
        name: "Stylish Sunglasses",
        price: 50,
        salePercentage: 20,
        image: "images/p7.jpg",
        smallImages: ["images/p7_thumb1.jpg", "images/p7_thumb2.jpg", "images/p7_thumb3.jpg"],
        category: "sale",
        size: "Medium",
        material: "plastic",
        style: "frameless",
        description: "Stylish sunglasses with UV protection."
    },
    {
        id: 24,
        name: "Classic Eyeframe",
        price: 70,
        salePercentage: 35,
        image: "images/p8.jpg",
        smallImages: ["images/p8_thumb1.jpg", "images/p8_thumb2.jpg", "images/p8_thumb3.jpg"],
        category: "eyeframes",
        size: "Large",
        material: "titan",
        style: "full-rim",
        description: "Classic eyeframe with a modern twist."
    },
    {
        id: 25,
        name: "Modern Sunglasses",
        price: 60,
        image: "images/p1.jpg",
        smallImages: ["images/p1_thumb1.jpg", "images/p1_thumb2.jpg", "images/p1_thumb3.jpg"],
        category: "sunglasses",
        size: "Small",
        material: "iron",
        style: "semi-rimless",
        description: "Modern sunglasses with a sleek design."
    },
    {
        id: 26,
        name: "Elegant Eyeframe",
        price: 80,
        image: "images/p2.jpg",
        smallImages: ["images/p2_thumb1.jpg", "images/p2_thumb2.jpg", "images/p2_thumb3.jpg"],
        category: "eyeframes",
        size: "Medium",
        material: "plastic",
        style: "combination",
        description: "Elegant eyeframe for a sophisticated look."
    },
    {
        id: 27,
        name: "Stylish Sunglasses",
        price: 50,
        salePercentage: 20,
        image: "images/p3.jpg",
        smallImages: ["images/p3_thumb1.jpg", "images/p3_thumb2.jpg", "images/p3_thumb3.jpg"],
        category: "sale",
        size: "Medium",
        material: "plastic",
        style: "frameless",
        description: "Stylish sunglasses with UV protection."
    },
    {
        id: 28,
        name: "Classic Eyeframe",
        price: 70,
        salePercentage: 35,
        image: "images/p4.jpg",
        smallImages: ["images/p4_thumb1.jpg", "images/p4_thumb2.jpg", "images/p4_thumb3.jpg"],
        category: "eyeframes",
        size: "Large",
        material: "titan",
        style: "full-rim",
        description: "Classic eyeframe with a modern twist."
    },
    {
        id: 29,
        name: "Modern Sunglasses",
        price: 60,
        image: "images/p5.jpg",
        smallImages: ["images/p5_thumb1.jpg", "images/p5_thumb2.jpg", "images/p5_thumb3.jpg"],
        category: "sunglasses",
        size: "Small",
        material: "iron",
        style: "semi-rimless",
        description: "Modern sunglasses with a sleek design."
    },
    {
        id: 30,
        name: "Elegant Eyeframe",
        price: 80,
        image: "images/p6.jpg",
        smallImages: ["images/p6_thumb1.jpg", "images/p6_thumb2.jpg", "images/p6_thumb3.jpg"],
        category: "eyeframes",
        size: "Medium",
        material: "plastic",
        style: "combination",
        description: "Elegant eyeframe for a sophisticated look."
    },
    {
        id: 31,
        name: "Stylish Sunglasses",
        price: 50,
        salePercentage: 20,
        image: "images/p7.jpg",
        smallImages: ["images/p7_thumb1.jpg", "images/p7_thumb2.jpg", "images/p7_thumb3.jpg"],
        category: "sale",
        size: "Medium",
        material: "plastic",
        style: "frameless",
        description: "Stylish sunglasses with UV protection."
    },
    {
        id: 32,
        name: "Classic Eyeframe",
        price: 70,
        salePercentage: 35,
        image: "images/p8.jpg",
        smallImages: ["images/p8_thumb1.jpg", "images/p8_thumb2.jpg", "images/p8_thumb3.jpg"],
        category: "eyeframes",
        size: "Large",
        material: "titan",
        style: "full-rim",
        description: "Classic eyeframe with a modern twist."
    },
        {
            id: 33,
            name: "Stylish Sunglasses",
            price: 50,
            salePercentage: 20,
            image: "images/p1.jpg",
            smallImages: ["images/p1_thumb1.jpg", "images/p1_thumb2.jpg", "images/p1_thumb3.jpg"],
            category: "sale",
            size: "Medium",
            material: "plastic",
            style: "frameless",
            description: "Stylish sunglasses with UV protection."
        },
        {
            id: 34,
            name: "Classic Eyeframe",
            price: 70,
            salePercentage: 35,
            image: "images/p2.jpg",
            smallImages: ["images/p2_thumb1.jpg", "images/p2_thumb2.jpg", "images/p2_thumb3.jpg"],
            category: "eyeframes",
            size: "Large",
            material: "titan",
            style: "full-rim",
            description: "Classic eyeframe with a modern twist."
        },
        {
            id: 35,
            name: "Modern Sunglasses",
            price: 60,
            image: "images/p3.jpg",
            smallImages: ["images/p3_thumb1.jpg", "images/p3_thumb2.jpg", "images/p3_thumb3.jpg"],
            category: "sunglasses",
            size: "Small",
            material: "iron",
            style: "semi-rimless",
            description: "Modern sunglasses with a sleek design."
        },
        {
            id: 36,
            name: "Elegant Eyeframe",
            price: 80,
            image: "images/p4.jpg",
            smallImages: ["images/p4_thumb1.jpg", "images/p4_thumb2.jpg", "images/p4_thumb3.jpg"],
            category: "eyeframes",
            size: "Medium",
            material: "plastic",
            style: "combination",
            description: "Elegant eyeframe for a sophisticated look."
        },
        {
            id: 37,
            name: "Elegant Eyeframe",
            price: 80,
            image: "images/p5.jpg",
            smallImages: ["images/p4_thumb1.jpg", "images/p4_thumb2.jpg", "images/p4_thumb3.jpg"],
            category: "eyeframes",
            size: "Medium",
            material: "titan",
            style: "half-eye",
            description: "Elegant eyeframe for a sophisticated look."
        },
        {
            id: 38,
            name: "Elegant Eyeframe",
            price: 80,
            salePercentage: 43,
            image: "images/p6.jpg",
            smallImages: ["images/p6.jpg", "images/p5.jpg", "images/p4.jpg"],
            category: "sale",
            size: "Medium",
            material: "iron",
            style: "low-bridge",
            description: "Elegant eyeframe for a sophisticated look."
        },
        {
            id: 39,
            name: "Trendy Sunglasses",
            price: 55,
            image: "images/p7.jpg",
            smallImages: ["images/p7_thumb1.jpg", "images/p7_thumb2.jpg", "images/p7_thumb3.jpg"],
            category: "sunglasses",
            size: "Large",
            material: "plastic",
            style: "full-rim",
            description: "Trendy sunglasses with a modern design."
        },
        {
            id: 40,
            name: "Vintage Eyeframe",
            price: 75,
            image: "images/p8.jpg",
            smallImages: ["images/p8_thumb1.jpg", "images/p8_thumb2.jpg", "images/p8_thumb3.jpg"],
            category: "eyeframes",
            size: "Small",
            material: "titan",
            style: "semi-rimless",
            description: "Vintage eyeframe with a classic look."
        },
        {
            id: 41,
            name: "Sporty Sunglasses",
            price: 65,
            image: "images/p1.jpg",
            smallImages: ["images/p1_thumb1.jpg", "images/p1_thumb2.jpg", "images/p1_thumb3.jpg"],
            category: "sunglasses",
            size: "Medium",
            material: "iron",
            style: "frameless",
            description: "Sporty sunglasses for active lifestyles."
        },
        {
            id: 42,
            name: "Luxury Eyeframe",
            price: 90,
            image: "images/p2.jpg",
            smallImages: ["images/p2_thumb1.jpg", "images/p2_thumb2.jpg", "images/p2_thumb3.jpg"],
            category: "eyeframes",
            size: "Large",
            material: "plastic",
            style: "combination",
            description: "Luxury eyeframe with premium materials."
        },
        {
            id: 43,
            name: "Casual Sunglasses",
            price: 45,
            salePercentage: 90,
            image: "images/p3.jpg",
            smallImages: ["images/p3_thumb1.jpg", "images/p3_thumb2.jpg", "images/p3_thumb3.jpg"],
            category: "sale",
            size: "Small",
            material: "titan",
            style: "full-rim",
            description: "Casual sunglasses for everyday wear."
        },
        {
            id: 44,
            name: "Professional Eyeframe",
            price: 85,
            image: "images/p4.jpg",
            smallImages: ["images/p4_thumb1.jpg", "images/p4_thumb2.jpg", "images/p4_thumb3.jpg"],
            category: "eyeframes",
            size: "Medium",
            material: "iron",
            style: "half-eye",
            description: "Professional eyeframe for a polished look."
        },
        {
            id: 45,
            name: "Chic Sunglasses",
            price: 70,
            image: "images/p5.jpg",
            smallImages: ["images/p5_thumb1.jpg", "images/p5_thumb2.jpg", "images/p5_thumb3.jpg"],
            category: "sunglasses",
            size: "Large",
            material: "plastic",
            style: "semi-rimless",
            description: "Chic sunglasses with a stylish design."
        },
        {
            id: 46,
            name: "Retro Eyeframe",
            price: 60,
            image: "images/p6.jpg",
            smallImages: ["images/p6_thumb1.jpg", "images/p6_thumb2.jpg", "images/p6_thumb3.jpg"],
            category: "eyeframes",
            size: "Small",
            material: "titan",
            style: "low-bridge",
            description: "Retro eyeframe with a vintage appeal."
        },
        {
            id: 47,
            name: "Bold Sunglasses",
            price: 75,
            image: "images/p7.jpg",
            smallImages: ["images/p7_thumb1.jpg", "images/p7_thumb2.jpg", "images/p7_thumb3.jpg"],
            category: "sale",
            size: "Medium",
            material: "iron",
            style: "full-rim",
            description: "Bold sunglasses for a confident look."
        },
        {
            id: 48,
            name: "Sophisticated Eyeframe",
            price: 95,
            image: "images/p8.jpg",
            smallImages: ["images/p8_thumb1.jpg", "images/p8_thumb2.jpg", "images/p8_thumb3.jpg"],
            category: "eyeframes",
            size: "Large",
            material: "plastic",
            style: "combination",
            description: "Sophisticated eyeframe for a refined style."
        },
        {
            id: 49,
            name: "Elegant Sunglasses",
            price: 80,
            image: "images/p1.jpg",
            smallImages: ["images/p1_thumb1.jpg", "images/p1_thumb2.jpg", "images/p1_thumb3.jpg"],
            category: "sunglasses",
            size: "Small",
            material: "titan",
            style: "frameless",
            description: "Elegant sunglasses with a sleek design."
        },
        {
            id: 50,
            name: "Modern Eyeframe",
            price: 65,
            image: "images/p2.jpg",
            smallImages: ["images/p2_thumb1.jpg", "images/p2_thumb2.jpg", "images/p2_thumb3.jpg"],
            category: "eyeframes",
            size: "Medium",
            material: "iron",
            style: "full-rim",
            description: "Modern eyeframe with a contemporary look."
        }
    ];
    